### PR TITLE
Add non-digital ocean setup instructions

### PR DESCRIPTION
**Pull request by aaronkuchma**
Setup instructions for non-digital ocean Ubuntu 16.04 installs.

Feel free to convert to html (to maintain colouring and other formatting) and rename rather than accept pull request.

### CODE REVIEW

**Comment by naconner** [comment]
Thanks! I'll convert this to a Wiki article.

**Comment by naconner** [comment]
@aaronkuchma Added here: https://github.com/lamassu/lamassu-install/wiki/Installing-onto-non-DigitalOcean-environments

Feel free to edit the wiki article if needed. Thanks again!

**Comment by fei115** [comment]
Hi @aaronkuchma, I have a question related to the ip address lamassu-server uses.

The lamassu-server installation scripts uses the following to the ip address:
`
IP=$(ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')
`
When i install lamassu-server on a DigitalOcean machine,  the inet addr is the public ip. But when I install it on my ubuntu machine, the inet addr is the private one (192.168.xxx.xxx).  I wonder how you resolved this problem?  Thank you very much!

**Comment by aaronkuchma** [comment]
There are two related issues. The first, getting access to that server from outside (either port routing / or via domain name with reverse proxying), the second is the certificate.

We opted to go with domain/reverse proxying, so when we generated our certificate, we had to keep the IP in it, but also had to modify the CN to reflect the domain name we assigned.

**Comment by aaronkuchma** [comment]
I think we may have had to edit the QR code to use the domain as well.

**Comment by fei115** [comment]
I think I will try out the port forwarding method. Probably going to replace the $IP with the actual public ip manually. Then port forward the following to the private ip address.
`
ufw allow 443/tcp >> $LOG_FILE 2>&1   # Admin
ufw allow 3000/tcp >> $LOG_FILE 2>&1  # Server
ufw allow 8071/tcp >> $LOG_FILE 2>&1  # Lamassu support
`
In case i have multiple servers, i think i can use a different port other than 3000 by modifying the QR Code(not too sure: https://support.lamassu.is/hc/en-us/articles/115001693145-Pairing-screen-error-or-pairing-QR-code-won-t-scan)

**Comment by knocte** [comment]
We tried the setup following https://github.com/lamassu/lamassu-install/wiki/Installing-onto-Ubuntu-Server-environments-other-than-DigitalOcean and got an error when continuing with https://support.lamassu.is/hc/en-us/articles/360007653892-Step-9-Installing-your-wallets , see:

```
$ lamassu-coins
? Which cryptocurrencies would you like to install? Bitcoin
Thanks! Installing: bitcoin. Will take a while...
Volume is already mounted.
Installing Bitcoin...
(node:825) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EACCES: permission denied, mkdir '/mnt/blockchains/bitcoin'
```

Seems like the fix to this is adding “sudo” to “lamassu-coins” command, so maybe you guys should consider adding this to the wiki.

**Comment by naconner** [comment]
Thanks for the notes, @knocte. Please feel free to update that wiki page with any findings or suggestions, it's publicly editable.

@fei115 The article you link to is largely in reference to our legacy version. I'll have that updated.

**Comment by fei115** [comment]
Thanks @naconner , that would be super helpful!

**Comment by tiuz1** [comment]
I am not able to install the lamassu Server on an Fresh install of ubuntu Server 16.0.4

I followed the instructions on the page but I am getting the following error in the log file:

`
12:01:00 Installing lamassu-server...
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/lamassu/lamassu-server.git
npm ERR!
npm ERR! fatal: failed to stat '.': Permission denied
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-10T10_01_03_489Z-debug.log

`
Is there any solution to this?

**Pull request closed without merging**
